/* In-scope services from the AIP-C01 exam guide, with the role each plays in GenAI solutions.
   [name, category, what it is for on this exam, "mix-up" warning] */
window.SERVICES = [
  ['Amazon Bedrock', 'Machine Learning', 'Managed access to FMs via Converse/InvokeModel; Guardrails, Knowledge Bases, Agents, Evaluations, Prompt Management, batch, Provisioned Throughput, cross-Region inference.', ''],
  ['Amazon Bedrock Knowledge Bases', 'Machine Learning', 'Managed RAG: connect data sources, chunk, embed, store in a vector store; Retrieve and RetrieveAndGenerate; hybrid search, reranking, metadata filters.', 'Not a database you manage; it orchestrates a vector store.'],
  ['Amazon Bedrock Prompt Management', 'Machine Learning', 'Versioned, parameterised prompt templates with variants; reference by ID/ARN.', 'Stores prompts; Prompt Flows chains them.'],
  ['Amazon Bedrock Prompt Flows', 'Machine Learning', 'Visual/no-code workflow builder chaining prompts, KBs, agents, Lambda, conditions.', 'Not for long-running human-approval workflows (Step Functions).'],
  ['Amazon Bedrock AgentCore', 'Machine Learning', 'Platform to run agents from any framework: Runtime, Memory, Gateway (APIs to MCP tools), Identity, Observability, Browser, Code Interpreter.', 'Not the same as Bedrock Agents (managed agent builder).'],
  ['Amazon Comprehend', 'Machine Learning', 'NLP: entities, sentiment, key phrases, language, PII detection/redaction, custom classification, intent-style classification.', 'Detects PII in text you send; Macie scans S3.'],
  ['Amazon Kendra', 'Machine Learning', 'Intelligent enterprise search with connectors; can act as a retriever for RAG.', 'Managed search; vs vector store you operate.'],
  ['Amazon Lex', 'Machine Learning', 'Conversational interfaces (intents, slots) for voice/text bots.', ''],
  ['Amazon Q Business', 'Machine Learning', 'Managed assistant over enterprise data with connectors and ACL-aware answers.', 'For employees using company data; Q Developer is for code.'],
  ['Amazon Q Business Apps', 'Machine Learning', 'No-code lightweight AI apps built from natural language within Q Business.', ''],
  ['Amazon Q Developer', 'Machine Learning', 'AI coding assistant: generate/refactor/test code, explain errors, security scans, upgrades.', 'Developer tool, not a runtime service.'],
  ['Amazon Quick', 'Machine Learning', 'AI-powered BI and assistants (Quick Sight dashboards, agentic workspace).', ''],
  ['Amazon Rekognition', 'Machine Learning', 'Image and video analysis (labels, faces, moderation).', ''],
  ['Amazon Textract', 'Machine Learning', 'Extract text, forms, tables from scanned documents.', ''],
  ['Amazon Transcribe', 'Machine Learning', 'Speech to text with speaker labels, custom vocabulary, PII redaction.', ''],
  ['Amazon Titan', 'Machine Learning', 'Amazon FM family: Text Embeddings V2 (256/512/1024 dims), Multimodal Embeddings, text and image generation.', ''],
  ['Amazon Augmented AI', 'Machine Learning', 'Human review workflows for ML predictions (human-in-the-loop).', 'A2I; routes low-confidence results to reviewers.'],
  ['Amazon SageMaker AI', 'Machine Learning', 'Build/train/host models; custom fine-tuning, endpoints (real-time, async, serverless), inference components, LMI containers.', 'Use when you need container/GPU control or open models.'],
  ['Amazon SageMaker Clarify', 'Machine Learning', 'Bias detection, explainability and FM evaluation.', ''],
  ['Amazon SageMaker Data Wrangler', 'Machine Learning', 'Visual data preparation and profiling.', ''],
  ['Amazon SageMaker Ground Truth', 'Machine Learning', 'Data labeling and human feedback/annotation workflows.', ''],
  ['Amazon SageMaker JumpStart', 'Machine Learning', 'Hub of pre-trained open and proprietary models with one-click deploy and fine-tune.', ''],
  ['Amazon SageMaker Model Monitor', 'Machine Learning', 'Detect data quality, model quality, bias and attribution drift on endpoints.', ''],
  ['Amazon SageMaker Model Registry', 'Machine Learning', 'Catalogue model versions with approval status for controlled deployment and rollback.', ''],
  ['Amazon SageMaker Neo', 'Machine Learning', 'Compile/optimise models for target hardware.', ''],
  ['Amazon SageMaker Processing', 'Machine Learning', 'Managed jobs for data processing, feature work and evaluation.', ''],
  ['Amazon SageMaker Unified Studio', 'Machine Learning', 'Integrated environment for data, analytics and AI development.', ''],
  ['Amazon Athena', 'Analytics', 'Serverless SQL over S3; handy target for text-to-SQL.', ''],
  ['Amazon EMR', 'Analytics', 'Managed big-data frameworks (Spark) for large-scale processing.', ''],
  ['AWS Glue', 'Analytics', 'ETL, Data Catalog, lineage, Glue Data Quality (DQDL rules).', ''],
  ['Amazon Kinesis', 'Analytics', 'Streaming ingestion and processing of real-time data.', ''],
  ['Amazon OpenSearch Service', 'Analytics', 'Search and vector engine: k-NN, hybrid search, neural plugin, sharding.', 'Full control vs Knowledge Bases managed.'],
  ['Amazon Quick Sight', 'Analytics', 'BI dashboards for metrics and reporting.', ''],
  ['Amazon MSK', 'Analytics', 'Managed Apache Kafka for streaming pipelines.', ''],
  ['Amazon AppFlow', 'Application Integration', 'Managed SaaS-to-AWS data flows (e.g., Salesforce to S3) for ingestion.', ''],
  ['AWS AppConfig', 'Application Integration', 'Dynamic configuration/feature flags with validation, gradual rollout and rollback.', 'Key for swapping models/prompt versions without redeploy.'],
  ['Amazon EventBridge', 'Application Integration', 'Event bus and scheduler for loosely coupled event-driven integrations.', ''],
  ['Amazon SNS', 'Application Integration', 'Pub/sub notifications and fan-out.', ''],
  ['Amazon SQS', 'Application Integration', 'Queues to buffer, decouple and retry asynchronous FM work; DLQ.', ''],
  ['AWS Step Functions', 'Application Integration', 'Orchestration: ReAct loops, circuit breakers, Retry/Catch, human approval (waitForTaskToken), model routing.', ''],
  ['AWS App Runner', 'Compute', 'Run containerised web apps/APIs with minimal ops.', ''],
  ['Amazon EC2', 'Compute', 'Virtual machines incl. GPU instances for self-managed inference.', ''],
  ['AWS Lambda', 'Compute', 'Serverless functions: webhooks, validation, tool executors, stateless MCP servers, post-processing.', '15-minute max duration.'],
  ['AWS Lambda@Edge', 'Compute', 'Run code at CloudFront edge locations.', ''],
  ['AWS Outposts', 'Compute', 'AWS infrastructure on premises for local data processing/low latency.', ''],
  ['AWS Wavelength', 'Compute', 'AWS compute at 5G edge for ultra-low latency.', ''],
  ['Amazon ECR', 'Containers', 'Container image registry.', ''],
  ['Amazon ECS', 'Containers', 'Container orchestration; hosts complex/stateful MCP servers or inference containers.', ''],
  ['Amazon EKS', 'Containers', 'Managed Kubernetes for container-based AI platforms.', ''],
  ['AWS Fargate', 'Containers', 'Serverless compute for containers (ECS/EKS).', ''],
  ['Amazon Connect', 'Customer Engagement', 'Cloud contact center; integrates Lex, Q in Connect, transcription.', ''],
  ['Amazon Aurora', 'Database', 'Relational DB; PostgreSQL edition with pgvector for vector search.', ''],
  ['Amazon DocumentDB', 'Database', 'Document database with vector search support.', ''],
  ['Amazon DynamoDB', 'Database', 'Key-value store for conversation history, metadata, caches, circuit-breaker state, TTL.', 'Not a vector index.'],
  ['Amazon DynamoDB Streams', 'Database', 'Change data capture to trigger index updates.', ''],
  ['Amazon ElastiCache', 'Database', 'In-memory cache; semantic/exact response caching.', ''],
  ['Amazon Neptune', 'Database', 'Graph database; Neptune Analytics supports GraphRAG.', ''],
  ['Amazon RDS', 'Database', 'Managed relational databases; PostgreSQL with pgvector.', ''],
  ['AWS Amplify', 'Developer Tools', 'Full-stack/front-end framework incl. AI Kit UI components.', ''],
  ['AWS CDK', 'Developer Tools', 'Infrastructure as code in programming languages.', ''],
  ['AWS CLI', 'Developer Tools', 'Command-line access to AWS APIs.', ''],
  ['AWS CloudFormation', 'Developer Tools', 'Declarative IaC templates and stacks.', ''],
  ['AWS CodeArtifact', 'Developer Tools', 'Managed package repositories.', ''],
  ['AWS CodeBuild', 'Developer Tools', 'Managed build/test service; runs evaluation and security scans.', ''],
  ['AWS CodeDeploy', 'Developer Tools', 'Automated deployments with rollback.', ''],
  ['AWS CodePipeline', 'Developer Tools', 'CI/CD orchestration with stages and quality gates.', ''],
  ['Kiro', 'Developer Tools', 'Agentic IDE with spec-driven development.', ''],
  ['AWS Tools and SDKs', 'Developer Tools', 'Language SDKs with built-in retries/backoff for Bedrock calls.', ''],
  ['AWS X-Ray', 'Developer Tools', 'Distributed tracing across API Gateway, Lambda and FM calls.', ''],
  ['AWS Auto Scaling', 'Management & Governance', 'Scale resources by demand/targets.', ''],
  ['AWS Chatbot', 'Management & Governance', 'Operational notifications/commands in Slack/Teams.', ''],
  ['AWS CloudTrail', 'Management & Governance', 'Audit log of API calls: who did what, when.', 'Not prompt content (use invocation logging).'],
  ['Amazon CloudWatch', 'Management & Governance', 'Metrics, alarms, dashboards, anomaly detection; AWS/Bedrock metrics.', ''],
  ['Amazon CloudWatch Logs', 'Management & Governance', 'Log storage and Logs Insights queries over invocation logs.', ''],
  ['Amazon CloudWatch Synthetics', 'Management & Governance', 'Canary scripts to test workflows from outside (synthetic users).', ''],
  ['AWS Cost Anomaly Detection', 'Management & Governance', 'Detect unusual spend automatically.', ''],
  ['AWS Cost Explorer', 'Management & Governance', 'Analyse cost and usage.', ''],
  ['Amazon Managed Grafana', 'Management & Governance', 'Managed dashboards across metrics sources.', ''],
  ['AWS Service Catalog', 'Management & Governance', 'Curated, approved products/templates for governed provisioning.', ''],
  ['AWS Systems Manager', 'Management & Governance', 'Operations tooling incl. Parameter Store for config.', ''],
  ['AWS Well-Architected Tool', 'Management & Governance', 'Review workloads against lenses incl. Generative AI Lens.', ''],
  ['AWS DataSync', 'Migration & Transfer', 'Move large datasets between on-prem and AWS storage.', ''],
  ['AWS Transfer Family', 'Migration & Transfer', 'SFTP/FTPS into S3/EFS for document intake.', ''],
  ['Amazon API Gateway', 'Networking & Delivery', 'Managed APIs: auth, throttling, usage plans, request validation, caching, WebSocket APIs.', ''],
  ['AWS AppSync', 'Networking & Delivery', 'Managed GraphQL with real-time subscriptions (stream tokens).', ''],
  ['Amazon CloudFront', 'Networking & Delivery', 'CDN and edge caching.', ''],
  ['Elastic Load Balancing', 'Networking & Delivery', 'Distribute traffic to containers/instances.', ''],
  ['AWS Global Accelerator', 'Networking & Delivery', 'Static anycast IPs and global routing over AWS network.', ''],
  ['AWS PrivateLink', 'Networking & Delivery', 'Private connectivity to services (interface VPC endpoints) without the internet.', ''],
  ['Amazon Route 53', 'Networking & Delivery', 'DNS with latency, failover and health-check routing.', ''],
  ['Amazon VPC', 'Networking & Delivery', 'Isolated virtual network; subnets, endpoints, security groups.', ''],
  ['Amazon Cognito', 'Security & Compliance', 'User sign-in, federation and temporary credentials for apps.', ''],
  ['AWS Encryption SDK', 'Security & Compliance', 'Client-side encryption library using envelope encryption.', ''],
  ['AWS IAM', 'Security & Compliance', 'Identities, policies, roles, least privilege; condition keys.', ''],
  ['IAM Access Analyzer', 'Security & Compliance', 'Find external/unused access; validate policies.', ''],
  ['IAM Identity Center', 'Security & Compliance', 'Workforce SSO and federation to AWS and apps.', ''],
  ['AWS KMS', 'Security & Compliance', 'Create and control encryption keys (CMKs) for data at rest.', ''],
  ['Amazon Macie', 'Security & Compliance', 'Discover sensitive data (PII) in S3.', 'S3 at rest, not live prompts.'],
  ['AWS Secrets Manager', 'Security & Compliance', 'Store and rotate credentials/API keys.', ''],
  ['AWS WAF', 'Security & Compliance', 'Web application firewall; rate-based and managed rules for APIs.', ''],
  ['Amazon EBS', 'Storage', 'Block storage for EC2.', ''],
  ['Amazon EFS', 'Storage', 'Shared file storage (e.g., model artifacts across containers).', ''],
  ['Amazon S3', 'Storage', 'Object storage for documents, datasets, prompt templates, logs; metadata; event triggers.', ''],
  ['Amazon S3 Intelligent-Tiering', 'Storage', 'Automatic cost optimisation across access tiers.', ''],
  ['Amazon S3 Lifecycle policies', 'Storage', 'Transition/expire objects: retention and cost control.', ''],
  ['Amazon S3 Cross-Region Replication', 'Storage', 'Replicate objects to another Region for residency/DR/latency.', '']
];
