const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.join(__dirname,'..');
function setup(){let time=1000000;const values=new Map();const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)};const context={window:{localStorage:storage},Date,Math,Map,Set,console};vm.createContext(context);for(const p of [...[1,2,3,4,5].map(i=>`js/data/exam${i}.js`),'js/lessons.js','js/exam-engine.js'])vm.runInContext(fs.readFileSync(path.join(root,p),'utf8'),context);return {engine:new context.window.ExamEngine(storage,()=>time),context,storage,advance:n=>time+=n};}
test('all 325 questions have valid keys, reasons, sources and responsive visuals',()=>{const {engine,context}=setup();let ids=new Set();for(const exam of Object.values(engine.exams)){assert.equal(exam.questions.length,65);assert.deepEqual([1,2,3,4,5].map(d=>exam.questions.filter(q=>q.domain===d).length),[13,16,18,9,9]);for(const type of ['single','multiple','ordering','matching'])assert.ok(exam.questions.some(q=>q.type===type));for(const q of exam.questions){assert.ok(!ids.has(q.id));ids.add(q.id);for(const field of ['scenario','question','explanation','subtopic'])assert.equal(typeof q[field],'string',q.id);assert.ok(q.options.length>=4);assert.equal(q.distractors.length,q.options.length,q.id);assert.ok(q.correctAnswers.every(i=>Number.isInteger(i)&&i>=0&&i<q.options.length));assert.equal(new Set(q.correctAnswers).size,q.correctAnswers.length);assert.ok(context.window.LESSONS[q.lessonId],q.id);assert.match(q.source,/^https:\/\/(docs\.)?aws\.amazon\.com\//);for(const suffix of ['', '-mobile'])assert.ok(fs.existsSync(path.join(root,`assets/lessons/${q.lessonId}${suffix}.svg`)));if(q.type==='matching')assert.equal(q.prompts.length,q.correctAnswers.length);}}assert.equal(ids.size,325);});
test('learning requires explicit complete check, locks first answer and records mistake',()=>{const {engine:e}=setup();e.start(1,'learning');const q=e.question();const wrong=q.options.findIndex((_,i)=>!q.correctAnswers.includes(i));e.select(wrong);assert.equal(e.state.revealed[q.id],undefined);assert.equal(e.check(),true);assert.ok(e.mistakes[q.id]);e.select(q.correctAnswers[0]);assert.equal(e.state.answers[q.id][0],wrong);assert.equal(e.score().correct,0);});
test('multi-response hides feedback until all choices are checked and requires exact match',()=>{const {engine:e}=setup();const q=e.exams[1].questions.find(q=>q.type==='multiple');e.start(1,'learning',[q.id]);e.select(q.correctAnswers[0]);assert.equal(e.check(),false);assert.equal(e.state.revealed[q.id],undefined);e.select(q.correctAnswers[1]);assert.equal(e.check(),true);assert.equal(e.score().correct,1);assert.equal(e.correct(q,[q.correctAnswers[0]]),false);});
test('ordering and matching score positions and reject incomplete input',()=>{const {engine:e}=setup();for(const type of ['ordering','matching']){const q=e.exams[1].questions.find(q=>q.type===type);e.start(1,'learning',[q.id]);e.assign(0,q.correctAnswers[0]);assert.equal(e.check(),false);q.correctAnswers.forEach((v,i)=>e.assign(i,v));assert.equal(e.complete(q),true);assert.equal(e.check(),true);assert.equal(e.score().correct,1);assert.equal(e.correct(q,[...q.correctAnswers].reverse()),false);}});
test('deadline persists across reload and expiration cannot reset the timer',()=>{const s=setup(),e=s.engine;e.start(1,'exam');s.advance(5399000);assert.equal(e.remaining(),1);e.save();const f=new s.context.window.ExamEngine(s.storage,()=>6400000);assert.equal(f.restore(),true);assert.equal(f.state.submitted,true);assert.equal(f.remaining(),0);assert.equal(f.history.length,1);f.submit();assert.equal(f.history.length,1);});
test('learning has no deadline; completed results are immutable and retry clears mistakes',()=>{const s=setup(),e=s.engine;e.start(1,'learning');s.advance(86400000);assert.equal(e.remaining(),null);assert.equal(e.expired(),false);const q=e.question();e.select(q.options.findIndex((_,i)=>!q.correctAnswers.includes(i)));e.check();e.submit();const result=e.score().percent;e.select(q.correctAnswers[0]);assert.equal(e.score().percent,result);e.start(1,'learning',[q.id]);q.correctAnswers.forEach(v=>e.select(v));e.check();assert.equal(e.mistakes[q.id],undefined);});
test('scores are raw, use all items and have no fabricated scaled score',()=>{const {engine:e}=setup();e.start(1,'exam');e.questions().forEach(q=>e.state.answers[q.id]=[...q.correctAnswers]);assert.equal(e.score().percent,100);e.state.answers[e.question().id]=[];assert.equal(e.score().correct,64);assert.equal(e.score().scaledScore,undefined);});
test('invalid option input, duplicate ordering, stale and corrupt sessions fail safely',()=>{const s=setup(),e=s.engine;e.start(1,'learning');e.select(200);assert.equal(e.state.answers[e.question().id],undefined);const q=e.exams[1].questions.find(q=>q.type==='ordering');e.start(1,'learning',[q.id]);q.options.forEach((_,i)=>e.assign(i,0));assert.equal(e.complete(q),false);s.storage.setItem('aif-session','{bad');assert.equal(e.restore(),false);s.storage.setItem('aif-session',JSON.stringify({version:1}));assert.equal(e.restore(),false);});
test('every option permutation is complete and resumes identically',()=>{const s=setup(),e=s.engine;e.start(3,'exam');for(const q of e.questions())assert.deepEqual(Array.from(e.state.optionOrder[q.id]).sort(),Array.from(q.options,(_,i)=>i).sort());const before=JSON.stringify(e.state.optionOrder);assert.equal(e.restore(),true);assert.equal(JSON.stringify(e.state.optionOrder),before);});
test('checked and unchecked learning answers remain distinct in final accuracy',()=>{const {engine:e}=setup();e.start(1,'learning');const q=e.question();e.select(q.correctAnswers[0]);e.submit();assert.equal(e.score().correct,0);assert.ok(e.mistakes[q.id]);});
